version: "3.8"

# Root compose for RiskNexus PoC
# - chroamdb service with persistent volume
# - placeholder FastAPI services for orchestrator + bots
# - all services share a custom network

services:
  postgres-db:
    image: postgres:16
    container_name: risknexus-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main
    ports:
      - "5432:5432" # This exposes the DB to your local machine (for pgAdmin)
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - risknexus_net

  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data_vol:/chroma/chroma
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 30s
      timeout: 5s
      retries: 1
    networks:
      - risknexus_net

  orchestrator:
    build: 
      context: .
      dockerfile: ./services/orchestrator/Dockerfile
    ports:
      - "8001:8000"
    networks:
      - risknexus_net
    environment:
      - WORKER_REQUEST_TIMEOUT=3600
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}

  sql-bot:
    build: 
      context: .
      dockerfile: ./services/sql-bot/Dockerfile
    networks:
      - risknexus_net
    environment:
      - WORKER_REQUEST_TIMEOUT=3600
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - CHROMA_URL=http://chromadb:8000
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  graph-bot:
    build: 
      context: .
      dockerfile: ./services/graph-bot/Dockerfile
    depends_on:
      chromadb:
        condition: service_healthy
    networks:
      - risknexus_net
    environment:
      - WORKER_REQUEST_TIMEOUT=3600
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - CHROMA_URL=http://chromadb:8000
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}

  search-bot:
    build: 
      context: .
      dockerfile: ./services/search-bot/Dockerfile
    networks:
      - risknexus_net
    environment:
      - WORKER_REQUEST_TIMEOUT=3600
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - CHROMA_URL=http://chromadb:8000

  doc-bot:
    build: 
      context: .
      dockerfile: ./services/doc-bot/Dockerfile
    networks:
      - risknexus_net
    environment:
      - WORKER_REQUEST_TIMEOUT=3600
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - CHROMA_URL=http://chromadb:8000

  #decision-bot:
  #  build: ./services/decision-bot
  #  networks:
  #    - risknexus_net
  #  environment:
  #    - WORKER_REQUEST_TIMEOUT=3600

  #calc-bot:
  #  build: ./services/calc-bot
  #  networks:
  #    - risknexus_net
  #  environment:
  #    - WORKER_REQUEST_TIMEOUT=3600

  embedding-bot:
    build: 
      context: .
      dockerfile: ./services/embedding-bot/Dockerfile
    depends_on:
      chromadb:
        condition: service_healthy
    networks:
      - risknexus_net
    ports:
      - "8003:8000"
    environment:
      - WORKER_REQUEST_TIMEOUT=3600
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - CHROMA_URL=http://chromadb:8000

networks:
  risknexus_net:
    driver: bridge

volumes:
  pg_data:
  chroma_data_vol: